apiVersion: plural.sh/v1alpha1
kind: Dependencies
metadata:
  application: true
  description: Deploys option-pool-frontend crafted for the target cloud
spec:
  dependencies:
  - type: helm
    name: bootstrap
    repo: bootstrap
    version: '>= 0.5.1'
  - type: helm
    name: option-pool-backend
    repo: option-pool
    version: ">= 0.1.0"
  - type: helm
    name: ingress-nginx
    repo: ingress-nginx
    version: ">= 0.1.2"
  - type: helm
    name: postgres
    repo: postgres
    version: ">= 0.1.6"
  - type: helm
    name: redis
    repo: redis
    version: '>= 0.1.6'
  - type: terraform
    name: aws
    repo: option-pool
    version: '>= 0.1.0'
    optional: true
  - type: terraform
    name: azure
    repo: option-pool
    version: '>= 0.1.0'
    optional: true
  - type: terraform
    name: gcp
    repo: option-pool
    version: '>= 0.1.0'
    optional: true
